### ISSUE TITLE
5e Spellblock Importer Error

### ISSUE THREAD

**Issue by biggusbeardus** [gioppoluca/5e-spellblock-importer#11]
Hello! I just added the 5e Spellblock Importer to my Foundry game. It worked for the first spell I imported, but does not work at all now. I just get an error telling me to report the problem. The format I am using meets the spellblock requirements.

I'm running the following:
Foundry VTT 12.331
D&D 5e 3.3.1
5E Spellblock Importer 1.3.5

I'm using Chrome Version 128.0.6613.85 (Official Build) (64-bit)

The console shows the text of the spell to be imported and the same error message that pops up on the Foundry screen, but I don't see anything else in the console. I'll add some screen shots. Something does look weird. The text of the spell shows 5 times after the click import command. Then it shows the error. I just don't understand why the first one worked perfectly and now I can't get ANY spell to work. Anyway, I hope this helps.

![chrome_UZ5irkHGw5](https://github.com/user-attachments/assets/db1fc666-0ff0-4412-b3b4-3591134b92a3)
![chrome_EprYkHJJDK](https://github.com/user-attachments/assets/29e58001-41d5-42ef-a2aa-1339c5071ba5)
![chrome_NmYn5IhKZi](https://github.com/user-attachments/assets/edff5c9a-1bd0-47a0-adc6-ec0407546c87)
![chrome_WaIoqdcITf](https://github.com/user-attachments/assets/f8919468-b45f-43fa-ba18-376d0c090323)

**Comment by gioppoluca** [comment]
fixed in 1.3.6
